# Site settings
theme: jekyll-theme-minimal
title: VI code
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 code code code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: vininn
github_username:  VinInn

# Build settings
markdown: kramdown
